io:
  logdir: logs/
  datadir: data/scannet-vp
  dataset: ScanNet
  resume_from:
  num_workers: 6
  tensorboard_port: 0
  validation_interval: 24000
  validation_debug: 240
  focal_length: 2.408333333333333
  num_vpts: 3
  augmentation_level: 2

model:
  batch_size: 8
  im2col_step: 21
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 1
  num_blocks: 1

  fc_channel: 1024

  # reg2classfication
  smp_pos: 1
  smp_neg: 1
  smp_rnd: 3
  smp_multiplier: 2
  multires:
    # those magic numbers are calculated by misc/find-radius.py
    - 0.0200483803479500
    - 0.0774278195486317
    - 0.2995648108645650
  output_stride: 4
  upsample_scale: 1

  conic_6x: True

optim:
  name: Adam
  lr: 1.0e-4
  amsgrad: True
  weight_decay: 1.0e-5
  max_epoch: 36
  lr_decay_epoch: 3
